
import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/tanstack-query-provider";
import LayoutWrapper from "@/components/common/layoutWrapper";
import ReactQueryProvider from "@/providers/tanstack-query-provider";
// import { CookiesProvider } from "react-cookie";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat.variable} antialiased`}
      >
        <main style={{ marginLeft: 0 }}>
          <ReactQueryProvider>
          <LayoutWrapper>
          <QueryProvider>{children}</QueryProvider>
          </LayoutWrapper>
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
}
